"""Imports every module's models so `Base.metadata` is complete.

Needed by two things that have to see the whole schema without going through the
running app:

* `migrations/env.py`, for `alembic revision --autogenerate`;
* `AUTO_CREATE_TABLES=1` in local development and tests.

This file sits at the `backend` package root rather than inside `backend/modules/`
because it is assembly-layer code, like server.py -- it is allowed to know that
every module exists, which no module itself is. Importing it from `backend.core`
would invert the dependency rule stated in `backend/modules/__init__.py`.

ADD A LINE HERE when a module gains its own models.py, or its tables will be
missing from autogenerated migrations -- silently, and only noticed the first time
something queries them in production.
"""

from backend.core.models import Base  # noqa: F401  (re-exported for convenience)

# Order is irrelevant to SQLAlchemy; grouped by phase for readability.
from backend.modules.academy import models as academy_models  # noqa: F401
from backend.modules.ai import models as ai_models  # noqa: F401
from backend.modules.constitution import models as constitution_models  # noqa: F401
from backend.modules.corrections import models as corrections_models  # noqa: F401
from backend.modules.events import models as events_models  # noqa: F401
from backend.modules.forum import models as forum_models  # noqa: F401
from backend.modules.legal import models as legal_models  # noqa: F401
from backend.modules.petitions import models as petitions_models  # noqa: F401
from backend.modules.reports import models as reports_models  # noqa: F401
from backend.modules.representatives import models as representatives_models  # noqa: F401
from backend.modules.research import models as research_models  # noqa: F401
from backend.modules.tools import models as tools_models  # noqa: F401
from backend.modules.volunteers import models as volunteers_models  # noqa: F401

__all__ = ["Base"]
