"""Phase 0: identity, RBAC, geography and the audit log

Hand-written rather than autogenerated because this is the first revision and
there is no database to diff against yet. Later revisions should use
`alembic revision --autogenerate` against a database already at head.

Revision ID: 0001_phase0
Revises:
Create Date: 2026-07-28
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

revision: str = "0001_phase0"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        "platform_meta",
        sa.Column("key", sa.String(length=60), primary_key=True),
        sa.Column("value", sa.Text(), nullable=False, server_default=""),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
    )

    op.create_table(
        "permissions",
        sa.Column("key", sa.String(length=80), primary_key=True),
        sa.Column("label", sa.String(length=160), nullable=False),
        sa.Column("category", sa.String(length=60), nullable=False, server_default="general"),
    )

    op.create_table(
        "roles",
        sa.Column("key", sa.String(length=60), primary_key=True),
        sa.Column("label", sa.String(length=120), nullable=False),
        sa.Column("description", sa.Text(), nullable=False, server_default=""),
        sa.Column("scoped", sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column("rank", sa.Integer(), nullable=False, server_default="0"),
    )

    op.create_table(
        "users",
        sa.Column("id", sa.String(length=36), primary_key=True),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False, server_default=""),
        sa.Column("active", sa.Boolean(), nullable=False, server_default=sa.true()),
        sa.Column("extra_permissions", sa.JSON(), nullable=False),
        sa.Column("is_bootstrap", sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.String(length=36), nullable=True),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.create_index("ix_users_email", "users", ["email"], unique=True)

    op.create_table(
        "role_permissions",
        sa.Column("id", sa.String(length=36), primary_key=True),
        sa.Column(
            "role_key",
            sa.String(length=60),
            sa.ForeignKey("roles.key", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "permission_key",
            sa.String(length=80),
            sa.ForeignKey("permissions.key", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.UniqueConstraint("role_key", "permission_key", name="uq_role_permission"),
    )

    op.create_table(
        "user_roles",
        sa.Column("id", sa.String(length=36), primary_key=True),
        sa.Column(
            "user_id", sa.String(length=36), sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False
        ),
        sa.Column(
            "role_key", sa.String(length=60), sa.ForeignKey("roles.key", ondelete="CASCADE"), nullable=False
        ),
        sa.Column("state_code", sa.String(length=10), nullable=True),
        sa.Column("district_code", sa.String(length=20), nullable=True),
        sa.Column("granted_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("granted_by", sa.String(length=36), nullable=True),
        sa.UniqueConstraint("user_id", "role_key", "state_code", "district_code", name="uq_user_role_scope"),
    )
    op.create_index("ix_user_roles_user", "user_roles", ["user_id"])

    op.create_table(
        "states",
        sa.Column("code", sa.String(length=10), primary_key=True),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("name_hi", sa.String(length=160), nullable=False, server_default=""),
        sa.Column("slug", sa.String(length=120), nullable=False, unique=True),
        sa.Column("is_union_territory", sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column("has_legislature", sa.Boolean(), nullable=False, server_default=sa.true()),
        sa.Column("lok_sabha_seats", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("rajya_sabha_seats", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("assembly_seats", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("is_pilot", sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column("campaign_stage", sa.String(length=40), nullable=False, server_default="no_demand"),
        sa.Column("campaign_note", sa.Text(), nullable=False, server_default=""),
        sa.Column("campaign_source_url", sa.Text(), nullable=True),
        sa.Column("campaign_updated_at", sa.DateTime(timezone=True), nullable=True),
    )

    op.create_table(
        "districts",
        sa.Column("code", sa.String(length=20), primary_key=True),
        sa.Column(
            "state_code",
            sa.String(length=10),
            sa.ForeignKey("states.code", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("name_hi", sa.String(length=160), nullable=False, server_default=""),
        sa.Column("slug", sa.String(length=140), nullable=False),
    )
    op.create_index("ix_districts_state", "districts", ["state_code"])

    op.create_table(
        "audit_log",
        sa.Column("id", sa.String(length=36), primary_key=True),
        sa.Column("actor_id", sa.String(length=36), nullable=True),
        sa.Column("actor_email", sa.String(length=255), nullable=False, server_default="system"),
        sa.Column("action", sa.String(length=60), nullable=False),
        sa.Column("entity_type", sa.String(length=60), nullable=False),
        sa.Column("entity_id", sa.String(length=120), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False, server_default=""),
        sa.Column("changes", sa.JSON(), nullable=True),
        sa.Column("source_url", sa.Text(), nullable=True),
        sa.Column("is_public", sa.Boolean(), nullable=False, server_default=sa.true()),
        sa.Column("ip_hash", sa.String(length=64), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    )
    op.create_index("ix_audit_entity", "audit_log", ["entity_type", "entity_id"])
    op.create_index("ix_audit_created", "audit_log", ["created_at"])
    # No foreign key from actor_id to users.id, by design: the audit log has to
    # outlive the accounts it describes. A cascade would erase the history of a
    # departed editor's work, and a restrict would block ever deleting them.


def downgrade() -> None:
    op.drop_table("audit_log")
    op.drop_index("ix_districts_state", table_name="districts")
    op.drop_table("districts")
    op.drop_table("states")
    op.drop_index("ix_user_roles_user", table_name="user_roles")
    op.drop_table("user_roles")
    op.drop_table("role_permissions")
    op.drop_index("ix_users_email", table_name="users")
    op.drop_table("users")
    op.drop_table("roles")
    op.drop_table("permissions")
    op.drop_table("platform_meta")
