"""Manifesto accountability: promises, RTIs, replies, documents, evidence, assessments

Adds the nine tables described in backend/modules/manifesto/models.py. The
existing schema is untouched -- no column on any Phase 0-5 table is altered, so
this revision is additive and its downgrade is a clean drop.

Written by hand rather than autogenerated (the machine this was built on has no
Python interpreter available to run `alembic revision --autogenerate`), so the
column list here was transcribed from the models and should be checked against
`alembic check` the first time it runs somewhere with a database.

WHAT THE DOWNGRADE COSTS: every RTI application, every government reply logged
against it and every assessment drawn from them. Those are records obtained under
the RTI Act over weeks; they exist nowhere else in this schema. The downgrade is
for a failed deploy on an empty database, not for routine use.

Revision ID: 0003_manifesto
Revises: 0002_platform_modules
Create Date: 2026-08-13
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

revision: str = "0003_manifesto"
down_revision: Union[str, None] = "0002_platform_modules"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        "manifesto_elections",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("slug", sa.String(length=120), nullable=False),
        sa.Column("state_code", sa.String(length=10), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("name_hi", sa.String(length=240), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("code_prefix", sa.String(length=8), nullable=False),
        sa.Column("house", sa.String(length=40), nullable=False),
        sa.Column("election_date", sa.Date(), nullable=True),
        sa.Column("result_date", sa.Date(), nullable=True),
        sa.Column("source_url", sa.Text(), nullable=False),
        sa.Column("is_published", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_manifesto_election_slug", "manifesto_elections", ["slug"], unique=True)
    op.create_index("ix_manifesto_election_state", "manifesto_elections", ["state_code"], unique=False)

    op.create_table(
        "manifestos",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("slug", sa.String(length=160), nullable=False),
        sa.Column("election_id", sa.String(length=36), nullable=False),
        sa.Column("party_code", sa.String(length=20), nullable=False),
        sa.Column("party_name", sa.String(length=200), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("title_hi", sa.String(length=360), nullable=False),
        sa.Column("published_on", sa.Date(), nullable=True),
        sa.Column("total_pages", sa.Integer(), nullable=True),
        sa.Column("source_url", sa.Text(), nullable=False),
        sa.Column("source_note", sa.Text(), nullable=False),
        sa.Column("is_published", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["election_id"], ["manifesto_elections.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_manifesto_slug", "manifestos", ["slug"], unique=True)
    op.create_index("ix_manifesto_election", "manifestos", ["election_id"], unique=False)

    op.create_table(
        "manifesto_promises",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("code", sa.String(length=40), nullable=False),
        sa.Column("election_id", sa.String(length=36), nullable=False),
        sa.Column("manifesto_id", sa.String(length=36), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("title_hi", sa.String(length=360), nullable=False),
        sa.Column("promise_text", sa.Text(), nullable=False),
        sa.Column("promise_text_hi", sa.Text(), nullable=False),
        sa.Column("manifesto_page", sa.String(length=40), nullable=False),
        sa.Column("manifesto_page_url", sa.Text(), nullable=False),
        sa.Column("department", sa.String(length=160), nullable=False),
        sa.Column("category", sa.String(length=120), nullable=False),
        sa.Column("tags", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("is_published", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["election_id"], ["manifesto_elections.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["manifesto_id"], ["manifestos.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code", name="uq_manifesto_promise_code"),
    )
    op.create_index("ix_promise_election", "manifesto_promises", ["election_id"], unique=False)
    op.create_index("ix_promise_status", "manifesto_promises", ["status"], unique=False)
    op.create_index("ix_promise_department", "manifesto_promises", ["department"], unique=False)

    op.create_table(
        "rti_applications",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("code", sa.String(length=40), nullable=False),
        sa.Column("promise_id", sa.String(length=36), nullable=False),
        sa.Column("subject", sa.String(length=300), nullable=False),
        sa.Column("public_authority", sa.String(length=240), nullable=False),
        sa.Column("department", sa.String(length=160), nullable=False),
        sa.Column("pio_designation", sa.String(length=240), nullable=False),
        sa.Column("application_number", sa.String(length=120), nullable=False),
        sa.Column("prepared_on", sa.Date(), nullable=True),
        sa.Column("filed_on", sa.Date(), nullable=True),
        sa.Column("reply_due_on", sa.Date(), nullable=True),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("application_url", sa.Text(), nullable=False),
        sa.Column("filing_proof_url", sa.Text(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=False),
        sa.Column("is_published", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["promise_id"], ["manifesto_promises.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code", name="uq_rti_code"),
    )
    op.create_index("ix_rti_promise", "rti_applications", ["promise_id"], unique=False)
    op.create_index("ix_rti_status", "rti_applications", ["status"], unique=False)

    op.create_table(
        "rti_responses",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("rti_id", sa.String(length=36), nullable=False),
        sa.Column("received_on", sa.Date(), nullable=True),
        sa.Column("reply_dated", sa.Date(), nullable=True),
        sa.Column("replying_authority", sa.String(length=240), nullable=False),
        sa.Column("department", sa.String(length=160), nullable=False),
        sa.Column("reference_number", sa.String(length=160), nullable=False),
        sa.Column("document_url", sa.Text(), nullable=False),
        sa.Column("page_count", sa.Integer(), nullable=True),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("is_appeal_reply", sa.Boolean(), nullable=False),
        sa.Column("is_published", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["rti_id"], ["rti_applications.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_rti_response_application", "rti_responses", ["rti_id"], unique=False)

    op.create_table(
        "government_documents",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("code", sa.String(length=40), nullable=False),
        sa.Column("promise_id", sa.String(length=36), nullable=True),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("kind", sa.String(length=60), nullable=False),
        sa.Column("issuing_authority", sa.String(length=240), nullable=False),
        sa.Column("department", sa.String(length=160), nullable=False),
        sa.Column("reference_number", sa.String(length=160), nullable=False),
        sa.Column("issued_on", sa.Date(), nullable=True),
        sa.Column("file_url", sa.Text(), nullable=False),
        sa.Column("source_note", sa.Text(), nullable=False),
        sa.Column("source_url", sa.Text(), nullable=False),
        sa.Column("obtained_via", sa.String(length=40), nullable=False),
        sa.Column("is_primary_source", sa.Boolean(), nullable=False),
        sa.Column("publisher", sa.String(length=160), nullable=False),
        sa.Column("page_count", sa.Integer(), nullable=True),
        sa.Column("is_published", sa.Boolean(), nullable=False),
        sa.Column("uploaded_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["promise_id"], ["manifesto_promises.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code", name="uq_government_document_code"),
    )
    op.create_index("ix_gov_doc_promise", "government_documents", ["promise_id"], unique=False)
    op.create_index("ix_gov_doc_kind", "government_documents", ["kind"], unique=False)

    op.create_table(
        "rti_questions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("rti_id", sa.String(length=36), nullable=False),
        sa.Column("number", sa.Integer(), nullable=False),
        sa.Column("question_text", sa.Text(), nullable=False),
        sa.Column("question_text_hi", sa.Text(), nullable=False),
        sa.Column("answer_text", sa.Text(), nullable=False),
        sa.Column("answer_status", sa.String(length=40), nullable=False),
        sa.Column("response_id", sa.String(length=36), nullable=True),
        sa.Column("supporting_document_id", sa.String(length=36), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["rti_id"], ["rti_applications.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["response_id"], ["rti_responses.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["supporting_document_id"], ["government_documents.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("rti_id", "number", name="uq_rti_question_number"),
    )
    op.create_index("ix_rti_question_application", "rti_questions", ["rti_id"], unique=False)

    op.create_table(
        "manifesto_evidence",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("promise_id", sa.String(length=36), nullable=False),
        sa.Column("document_id", sa.String(length=36), nullable=True),
        sa.Column("rti_question_id", sa.String(length=36), nullable=True),
        sa.Column("statement", sa.Text(), nullable=False),
        sa.Column("statement_hi", sa.Text(), nullable=False),
        sa.Column("locator", sa.String(length=160), nullable=False),
        sa.Column("recorded_on", sa.Date(), nullable=True),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("is_published", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["promise_id"], ["manifesto_promises.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["document_id"], ["government_documents.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["rti_question_id"], ["rti_questions.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_evidence_promise", "manifesto_evidence", ["promise_id"], unique=False)
    op.create_index("ix_evidence_document", "manifesto_evidence", ["document_id"], unique=False)

    op.create_table(
        "promise_assessments",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("promise_id", sa.String(length=36), nullable=False),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("rationale", sa.Text(), nullable=False),
        sa.Column("method_note", sa.Text(), nullable=False),
        sa.Column("sources", sa.JSON(), nullable=False),
        sa.Column("assessed_on", sa.Date(), nullable=True),
        sa.Column("assessed_by", sa.String(length=36), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("is_current", sa.Boolean(), nullable=False),
        sa.Column("is_published", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["promise_id"], ["manifesto_promises.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_assessment_promise", "promise_assessments", ["promise_id"], unique=False)
    op.create_index(
        "ix_assessment_current", "promise_assessments", ["promise_id", "is_current"], unique=False
    )


def downgrade() -> None:
    op.drop_table("promise_assessments")
    op.drop_table("manifesto_evidence")
    op.drop_table("rti_questions")
    op.drop_table("government_documents")
    op.drop_table("rti_responses")
    op.drop_table("rti_applications")
    op.drop_table("manifesto_promises")
    op.drop_table("manifestos")
    op.drop_table("manifesto_elections")
