"""Phase 1-5: the platform modules

Adds every table for the modules described in §4 of IMPLEMENTATION_PLAN.md:
constitution, representatives (with the citation-gated claim store), promises,
corrections, petitions, citizen reports, forum, volunteers, events, academy,
research/media, tools, the AI answer cache, DPDP consent records, plus the three
shared core tables the modules depend on (citizens, certificates, search_docs).

Autogenerated against revision 0001 and then trimmed by hand in two ways:

* The `alter_column` statements autogenerate proposed were DROPPED. They wanted to
  remove the `server_default` values revision 0001 set on the Phase-0 tables --
  which the models do not declare, because they use Python-side defaults instead.
  Removing them would be a schema change to live tables with no behavioural
  benefit, so this revision leaves the Phase-0 tables completely untouched.
* The downgrade drops the new tables in reverse dependency order. It is written to
  work, but note that dropping these loses the constitution library, every
  representative profile and the whole community side; it exists for a failed
  deploy, not as a routine operation.

Revision ID: 0002_platform_modules
Revises: 0001_phase0
Create Date: 2026-08-09
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

revision: str = "0002_platform_modules"
down_revision: Union[str, None] = "0001_phase0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table('academy_courses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('slug', sa.String(length=220), nullable=False),
    sa.Column('title', sa.String(length=240), nullable=False),
    sa.Column('title_hi', sa.String(length=300), nullable=False),
    sa.Column('summary', sa.String(length=600), nullable=False),
    sa.Column('summary_hi', sa.String(length=700), nullable=False),
    sa.Column('level', sa.String(length=20), nullable=False),
    sa.Column('estimated_minutes', sa.Integer(), nullable=False),
    sa.Column('cover_url', sa.Text(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_course_slug', 'academy_courses', ['slug'], unique=True)
    op.create_table('ai_answer_cache',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('question_hash', sa.String(length=64), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('citations', sa.JSON(), nullable=False),
    sa.Column('engine', sa.String(length=20), nullable=False),
    sa.Column('hit_count', sa.Integer(), nullable=False),
    sa.Column('is_reviewed', sa.Boolean(), nullable=False),
    sa.Column('is_pinned', sa.Boolean(), nullable=False),
    sa.Column('reviewed_by', sa.String(length=36), nullable=True),
    sa.Column('review_note', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ai_cache_key', 'ai_answer_cache', ['question_hash'], unique=True)
    op.create_table('ai_question_log',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('was_cached', sa.Boolean(), nullable=False),
    sa.Column('was_answered', sa.Boolean(), nullable=False),
    sa.Column('refusal_reason', sa.String(length=40), nullable=False),
    sa.Column('engine', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ai_log_created', 'ai_question_log', ['created_at'], unique=False)
    op.create_table('certificates',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=24), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('citizen_id', sa.String(length=36), nullable=True),
    sa.Column('holder_email', sa.String(length=255), nullable=False),
    sa.Column('holder_name', sa.String(length=160), nullable=False),
    sa.Column('title', sa.String(length=240), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('issued_by', sa.String(length=36), nullable=True),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('revoked_reason', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_certificate_code', 'certificates', ['code'], unique=True)
    op.create_index('ix_certificate_holder', 'certificates', ['citizen_id'], unique=False)
    op.create_table('citizens',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=60), nullable=False),
    sa.Column('state_code', sa.String(length=10), nullable=True),
    sa.Column('reputation', sa.Integer(), nullable=False),
    sa.Column('contributions', sa.JSON(), nullable=False),
    sa.Column('muted_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('muted_reason', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_citizens_email'), 'citizens', ['email'], unique=True)
    op.create_table('consent_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('subject_email', sa.String(length=255), nullable=False),
    sa.Column('purpose', sa.String(length=40), nullable=False),
    sa.Column('granted', sa.Boolean(), nullable=False),
    sa.Column('policy_version', sa.String(length=20), nullable=False),
    sa.Column('notice_shown', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=80), nullable=False),
    sa.Column('ip_hash', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_consent_created', 'consent_records', ['created_at'], unique=False)
    op.create_index('ix_consent_subject', 'consent_records', ['subject_email', 'purpose'], unique=False)
    op.create_table('constitution_articles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('number', sa.String(length=20), nullable=False),
    sa.Column('sort_key', sa.Integer(), nullable=False),
    sa.Column('part', sa.String(length=20), nullable=False),
    sa.Column('part_title', sa.String(length=160), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('title_hi', sa.String(length=400), nullable=False),
    sa.Column('original_text', sa.Text(), nullable=False),
    sa.Column('original_source_url', sa.Text(), nullable=False),
    sa.Column('plain_en', sa.Text(), nullable=False),
    sa.Column('plain_hi', sa.Text(), nullable=False),
    sa.Column('recall_relevance', sa.Text(), nullable=False),
    sa.Column('case_law', sa.JSON(), nullable=False),
    sa.Column('amendments', sa.JSON(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('related', sa.JSON(), nullable=False),
    sa.Column('translation_status', sa.JSON(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_constitution_number', 'constitution_articles', ['number'], unique=True)
    op.create_index('ix_constitution_part', 'constitution_articles', ['part'], unique=False)
    op.create_index('ix_constitution_published', 'constitution_articles', ['is_published'], unique=False)
    op.create_table('corrections',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('entity_type', sa.String(length=40), nullable=False),
    sa.Column('entity_id', sa.String(length=120), nullable=False),
    sa.Column('field_key', sa.String(length=60), nullable=False),
    sa.Column('summary', sa.String(length=300), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('proposed_value', sa.Text(), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('source_title', sa.String(length=300), nullable=False),
    sa.Column('citizen_id', sa.String(length=36), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('resolution_note', sa.Text(), nullable=False),
    sa.Column('resulted_in', sa.String(length=120), nullable=False),
    sa.Column('policy_flags', sa.Text(), nullable=False),
    sa.Column('reviewed_by', sa.String(length=36), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_correction_entity', 'corrections', ['entity_type', 'entity_id'], unique=False)
    op.create_index('ix_correction_status', 'corrections', ['status'], unique=False)
    op.create_table('events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('slug', sa.String(length=220), nullable=False),
    sa.Column('title', sa.String(length=240), nullable=False),
    sa.Column('title_hi', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('state_code', sa.String(length=10), nullable=True),
    sa.Column('district_code', sa.String(length=20), nullable=True),
    sa.Column('is_online', sa.Boolean(), nullable=False),
    sa.Column('venue', sa.String(length=240), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('meeting_url', sa.Text(), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('registration_count', sa.Integer(), nullable=False),
    sa.Column('attended_count', sa.Integer(), nullable=False),
    sa.Column('organiser_name', sa.String(length=160), nullable=False),
    sa.Column('organiser_contact', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('cancellation_reason', sa.Text(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_event_slug', 'events', ['slug'], unique=True)
    op.create_index('ix_event_state', 'events', ['state_code'], unique=False)
    op.create_index('ix_event_when', 'events', ['starts_at'], unique=False)
    op.create_table('forum_categories',
    sa.Column('key', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('name_hi', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_locked', sa.Boolean(), nullable=False),
    sa.Column('min_reputation', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('parties',
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('name_hi', sa.String(length=240), nullable=False),
    sa.Column('eci_status', sa.String(length=30), nullable=False),
    sa.Column('symbol', sa.String(length=120), nullable=False),
    sa.Column('founded_year', sa.Integer(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('petitions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('slug', sa.String(length=220), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('title_hi', sa.String(length=360), nullable=False),
    sa.Column('summary', sa.String(length=600), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('body_hi', sa.Text(), nullable=False),
    sa.Column('addressed_to', sa.String(length=300), nullable=False),
    sa.Column('state_code', sa.String(length=10), nullable=True),
    sa.Column('category', sa.String(length=60), nullable=False),
    sa.Column('target_signatures', sa.Integer(), nullable=False),
    sa.Column('signature_count', sa.Integer(), nullable=False),
    sa.Column('citizen_id', sa.String(length=36), nullable=True),
    sa.Column('is_official', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('status_note', sa.Text(), nullable=False),
    sa.Column('outcome_source_url', sa.Text(), nullable=False),
    sa.Column('milestones', sa.JSON(), nullable=False),
    sa.Column('policy_flags', sa.Text(), nullable=False),
    sa.Column('closes_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reviewed_by', sa.String(length=36), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_petition_slug', 'petitions', ['slug'], unique=True)
    op.create_index('ix_petition_state', 'petitions', ['state_code'], unique=False)
    op.create_index('ix_petition_status', 'petitions', ['status'], unique=False)
    op.create_table('research_documents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('slug', sa.String(length=240), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('title_hi', sa.String(length=360), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('summary_hi', sa.Text(), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('authors', sa.String(length=300), nullable=False),
    sa.Column('publisher', sa.String(length=200), nullable=False),
    sa.Column('published_on', sa.Date(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('file_url', sa.Text(), nullable=False),
    sa.Column('file_type', sa.String(length=40), nullable=False),
    sa.Column('file_size_kb', sa.Integer(), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('licence', sa.String(length=30), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('state_code', sa.String(length=10), nullable=True),
    sa.Column('article_refs', sa.JSON(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('download_count', sa.Integer(), nullable=False),
    sa.Column('uploaded_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_document_kind', 'research_documents', ['kind'], unique=False)
    op.create_index('ix_document_published', 'research_documents', ['is_published'], unique=False)
    op.create_index('ix_document_slug', 'research_documents', ['slug'], unique=True)
    op.create_index('ix_document_state', 'research_documents', ['state_code'], unique=False)
    op.create_table('search_docs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('entity_type', sa.String(length=40), nullable=False),
    sa.Column('entity_id', sa.String(length=120), nullable=False),
    sa.Column('locale', sa.String(length=10), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('subtitle', sa.String(length=400), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('keywords', sa.Text(), nullable=False),
    sa.Column('url_path', sa.String(length=300), nullable=False),
    sa.Column('state_code', sa.String(length=10), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_type', 'entity_id', 'locale', name='uq_search_entity_locale')
    )
    op.create_index('ix_search_state', 'search_docs', ['state_code'], unique=False)
    op.create_index('ix_search_type', 'search_docs', ['entity_type'], unique=False)
    op.create_table('tool_generation_log',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('template_key', sa.String(length=60), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('state_code', sa.String(length=10), nullable=True),
    sa.Column('output_format', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_generation_template', 'tool_generation_log', ['template_key', 'created_at'], unique=False)
    op.create_table('tool_templates',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('key', sa.String(length=60), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=240), nullable=False),
    sa.Column('title_hi', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('state_code', sa.String(length=10), nullable=True),
    sa.Column('fields', sa.JSON(), nullable=False),
    sa.Column('body', sa.JSON(), nullable=False),
    sa.Column('legal_basis', sa.Text(), nullable=False),
    sa.Column('filing_notes', sa.Text(), nullable=False),
    sa.Column('review_status', sa.String(length=20), nullable=False),
    sa.Column('reviewed_by', sa.String(length=36), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('review_note', sa.Text(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_seeded', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_template_key', 'tool_templates', ['key'], unique=True)
    op.create_index('ix_template_kind', 'tool_templates', ['kind', 'review_status'], unique=False)
    op.create_table('volunteer_tasks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('slug', sa.String(length=220), nullable=False),
    sa.Column('title', sa.String(length=240), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('skill', sa.String(length=30), nullable=False),
    sa.Column('acceptance_criteria', sa.Text(), nullable=False),
    sa.Column('state_code', sa.String(length=10), nullable=True),
    sa.Column('district_code', sa.String(length=20), nullable=True),
    sa.Column('is_remote', sa.Boolean(), nullable=False),
    sa.Column('estimated_hours', sa.Float(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('claimed_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('due_on', sa.Date(), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_task_skill_status', 'volunteer_tasks', ['skill', 'status'], unique=False)
    op.create_index('ix_task_slug', 'volunteer_tasks', ['slug'], unique=True)
    op.create_index('ix_task_state', 'volunteer_tasks', ['state_code'], unique=False)
    op.create_table('academy_enrollments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('course_id', sa.String(length=36), nullable=False),
    sa.Column('citizen_id', sa.String(length=36), nullable=False),
    sa.Column('completed_lessons', sa.JSON(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['citizen_id'], ['citizens.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['course_id'], ['academy_courses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('course_id', 'citizen_id', name='uq_enrollment')
    )
    op.create_index('ix_enrollment_citizen', 'academy_enrollments', ['citizen_id'], unique=False)
    op.create_table('academy_lessons',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('course_id', sa.String(length=36), nullable=False),
    sa.Column('slug', sa.String(length=160), nullable=False),
    sa.Column('title', sa.String(length=240), nullable=False),
    sa.Column('title_hi', sa.String(length=300), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('body_hi', sa.Text(), nullable=False),
    sa.Column('article_refs', sa.JSON(), nullable=False),
    sa.Column('video_ids', sa.JSON(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('minutes', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['academy_courses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('course_id', 'slug', name='uq_lesson_slug')
    )
    op.create_index('ix_lesson_course', 'academy_lessons', ['course_id', 'sort_order'], unique=False)
    op.create_table('academy_quizzes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('course_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=240), nullable=False),
    sa.Column('pass_percent', sa.Integer(), nullable=False),
    sa.Column('questions', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['academy_courses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('course_id', name='uq_quiz_course')
    )
    op.create_table('citizen_reports',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('slug', sa.String(length=220), nullable=False),
    sa.Column('citizen_id', sa.String(length=36), nullable=False),
    sa.Column('show_author', sa.Boolean(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('service', sa.String(length=40), nullable=False),
    sa.Column('state_code', sa.String(length=10), nullable=False),
    sa.Column('district_code', sa.String(length=20), nullable=True),
    sa.Column('constituency_code', sa.String(length=30), nullable=True),
    sa.Column('locality', sa.String(length=200), nullable=False),
    sa.Column('representative_id', sa.String(length=36), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('verification_note', sa.Text(), nullable=False),
    sa.Column('verified_by', sa.String(length=36), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('response_text', sa.Text(), nullable=False),
    sa.Column('response_from', sa.String(length=200), nullable=False),
    sa.Column('response_source_url', sa.Text(), nullable=False),
    sa.Column('response_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('policy_flags', sa.Text(), nullable=False),
    sa.Column('upvotes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['citizen_id'], ['citizens.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_report_place', 'citizen_reports', ['state_code', 'district_code'], unique=False)
    op.create_index('ix_report_service', 'citizen_reports', ['service'], unique=False)
    op.create_index('ix_report_slug', 'citizen_reports', ['slug'], unique=True)
    op.create_index('ix_report_status', 'citizen_reports', ['status'], unique=False)
    op.create_table('constituencies',
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('state_code', sa.String(length=10), nullable=False),
    sa.Column('district_code', sa.String(length=20), nullable=True),
    sa.Column('house', sa.String(length=20), nullable=False),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('name_hi', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=180), nullable=False),
    sa.Column('reserved_for', sa.String(length=10), nullable=True),
    sa.Column('electors', sa.Integer(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['state_code'], ['states.code'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('code'),
    sa.UniqueConstraint('state_code', 'house', 'number', name='uq_constituency_number')
    )
    op.create_index('ix_constituency_slug', 'constituencies', ['slug'], unique=True)
    op.create_index('ix_constituency_state_house', 'constituencies', ['state_code', 'house'], unique=False)
    op.create_table('event_registrations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('event_id', sa.String(length=36), nullable=False),
    sa.Column('citizen_id', sa.String(length=36), nullable=False),
    sa.Column('ticket_code', sa.String(length=24), nullable=False),
    sa.Column('name_snapshot', sa.String(length=160), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('checked_in_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('checked_in_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['citizen_id'], ['citizens.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'citizen_id', name='uq_event_registration')
    )
    op.create_index('ix_registration_event', 'event_registrations', ['event_id'], unique=False)
    op.create_index('ix_registration_ticket', 'event_registrations', ['ticket_code'], unique=True)
    op.create_table('forum_threads',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('slug', sa.String(length=220), nullable=False),
    sa.Column('category_key', sa.String(length=40), nullable=False),
    sa.Column('citizen_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('state_code', sa.String(length=10), nullable=True),
    sa.Column('subject_ref', sa.String(length=140), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('is_pinned', sa.Boolean(), nullable=False),
    sa.Column('is_locked', sa.Boolean(), nullable=False),
    sa.Column('reply_count', sa.Integer(), nullable=False),
    sa.Column('upvotes', sa.Integer(), nullable=False),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('policy_flags', sa.Text(), nullable=False),
    sa.Column('moderation_note', sa.Text(), nullable=False),
    sa.Column('moderated_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['category_key'], ['forum_categories.key'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['citizen_id'], ['citizens.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_thread_category', 'forum_threads', ['category_key', 'last_activity_at'], unique=False)
    op.create_index('ix_thread_slug', 'forum_threads', ['slug'], unique=True)
    op.create_index('ix_thread_status', 'forum_threads', ['status'], unique=False)
    op.create_table('forum_votes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('target_type', sa.String(length=10), nullable=False),
    sa.Column('target_id', sa.String(length=36), nullable=False),
    sa.Column('citizen_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['citizen_id'], ['citizens.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('target_type', 'target_id', 'citizen_id', name='uq_forum_vote')
    )
    op.create_index('ix_vote_target', 'forum_votes', ['target_type', 'target_id'], unique=False)
    op.create_table('petition_signatures',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('petition_id', sa.String(length=36), nullable=False),
    sa.Column('citizen_id', sa.String(length=36), nullable=False),
    sa.Column('display_name', sa.String(length=60), nullable=False),
    sa.Column('state_code', sa.String(length=10), nullable=True),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('comment_hidden', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['citizen_id'], ['citizens.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['petition_id'], ['petitions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('petition_id', 'citizen_id', name='uq_petition_signature')
    )
    op.create_index('ix_signature_petition', 'petition_signatures', ['petition_id'], unique=False)
    op.create_table('volunteer_profiles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('citizen_id', sa.String(length=36), nullable=False),
    sa.Column('skills', sa.JSON(), nullable=False),
    sa.Column('languages', sa.JSON(), nullable=False),
    sa.Column('hours_per_week', sa.Integer(), nullable=True),
    sa.Column('state_code', sa.String(length=10), nullable=True),
    sa.Column('district_code', sa.String(length=20), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=False),
    sa.Column('bio', sa.Text(), nullable=False),
    sa.Column('verified_hours', sa.Float(), nullable=False),
    sa.Column('completed_tasks', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['citizen_id'], ['citizens.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('citizen_id', name='uq_volunteer_citizen')
    )
    op.create_index('ix_volunteer_state', 'volunteer_profiles', ['state_code'], unique=False)
    op.create_table('academy_quiz_attempts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('quiz_id', sa.String(length=36), nullable=False),
    sa.Column('citizen_id', sa.String(length=36), nullable=False),
    sa.Column('score_percent', sa.Float(), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('answers', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['citizen_id'], ['citizens.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['quiz_id'], ['academy_quizzes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_attempt_citizen', 'academy_quiz_attempts', ['citizen_id', 'quiz_id'], unique=False)
    op.create_table('forum_replies',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('thread_id', sa.String(length=36), nullable=False),
    sa.Column('citizen_id', sa.String(length=36), nullable=False),
    sa.Column('parent_id', sa.String(length=36), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('upvotes', sa.Integer(), nullable=False),
    sa.Column('policy_flags', sa.Text(), nullable=False),
    sa.Column('moderation_note', sa.Text(), nullable=False),
    sa.Column('moderated_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['citizen_id'], ['citizens.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['thread_id'], ['forum_threads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_reply_status', 'forum_replies', ['status'], unique=False)
    op.create_index('ix_reply_thread', 'forum_replies', ['thread_id', 'created_at'], unique=False)
    op.create_table('report_confirmations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('report_id', sa.String(length=36), nullable=False),
    sa.Column('citizen_id', sa.String(length=36), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['citizen_id'], ['citizens.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['report_id'], ['citizen_reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_confirmation_report', 'report_confirmations', ['report_id'], unique=False)
    op.create_index('ix_confirmation_unique', 'report_confirmations', ['report_id', 'citizen_id'], unique=True)
    op.create_table('representatives',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('name_hi', sa.String(length=240), nullable=False),
    sa.Column('slug', sa.String(length=220), nullable=False),
    sa.Column('photo_url', sa.Text(), nullable=False),
    sa.Column('house', sa.String(length=20), nullable=False),
    sa.Column('state_code', sa.String(length=10), nullable=False),
    sa.Column('constituency_code', sa.String(length=30), nullable=True),
    sa.Column('party_code', sa.String(length=20), nullable=True),
    sa.Column('term_start', sa.Date(), nullable=True),
    sa.Column('term_end', sa.Date(), nullable=True),
    sa.Column('is_sitting', sa.Boolean(), nullable=False),
    sa.Column('office', sa.String(length=200), nullable=False),
    sa.Column('official_email', sa.String(length=255), nullable=False),
    sa.Column('office_address', sa.Text(), nullable=False),
    sa.Column('official_page_url', sa.Text(), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('source_title', sa.String(length=300), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['constituency_code'], ['constituencies.code'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['party_code'], ['parties.code'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_rep_constituency', 'representatives', ['constituency_code'], unique=False)
    op.create_index('ix_rep_published', 'representatives', ['is_published'], unique=False)
    op.create_index('ix_rep_slug', 'representatives', ['slug'], unique=True)
    op.create_index('ix_rep_state_house', 'representatives', ['state_code', 'house'], unique=False)
    op.create_table('task_assignments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('task_id', sa.String(length=36), nullable=False),
    sa.Column('profile_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('submission_note', sa.Text(), nullable=False),
    sa.Column('submission_url', sa.Text(), nullable=False),
    sa.Column('hours_claimed', sa.Float(), nullable=False),
    sa.Column('hours_verified', sa.Float(), nullable=False),
    sa.Column('review_note', sa.Text(), nullable=False),
    sa.Column('verified_by', sa.String(length=36), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['volunteer_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['volunteer_tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id', 'profile_id', name='uq_task_assignment')
    )
    op.create_index('ix_assignment_profile', 'task_assignments', ['profile_id'], unique=False)
    op.create_index('ix_assignment_status', 'task_assignments', ['status'], unique=False)
    op.create_table('promises',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('slug', sa.String(length=220), nullable=False),
    sa.Column('representative_id', sa.String(length=36), nullable=True),
    sa.Column('party_code', sa.String(length=20), nullable=True),
    sa.Column('state_code', sa.String(length=10), nullable=True),
    sa.Column('constituency_code', sa.String(length=30), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('title_hi', sa.String(length=360), nullable=False),
    sa.Column('promise_text', sa.Text(), nullable=False),
    sa.Column('promise_text_hi', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=60), nullable=False),
    sa.Column('made_on', sa.Date(), nullable=True),
    sa.Column('made_context', sa.String(length=200), nullable=False),
    sa.Column('deadline', sa.Date(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('source_title', sa.String(length=300), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('status_note', sa.Text(), nullable=False),
    sa.Column('status_source_url', sa.Text(), nullable=False),
    sa.Column('status_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verification_status', sa.String(length=20), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['party_code'], ['parties.code'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['representative_id'], ['representatives.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_promise_rep', 'promises', ['representative_id'], unique=False)
    op.create_index('ix_promise_slug', 'promises', ['slug'], unique=True)
    op.create_index('ix_promise_state_status', 'promises', ['state_code', 'status'], unique=False)
    op.create_table('representative_claims',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('representative_id', sa.String(length=36), nullable=False),
    sa.Column('field_key', sa.String(length=60), nullable=False),
    sa.Column('period', sa.String(length=40), nullable=False),
    sa.Column('value_number', sa.Float(), nullable=True),
    sa.Column('value_text', sa.Text(), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('source_title', sa.String(length=300), nullable=False),
    sa.Column('source_date', sa.String(length=12), nullable=False),
    sa.Column('source_publisher', sa.String(length=160), nullable=False),
    sa.Column('source_is_primary', sa.Boolean(), nullable=False),
    sa.Column('verification_status', sa.String(length=20), nullable=False),
    sa.Column('review_note', sa.Text(), nullable=False),
    sa.Column('submitted_by', sa.String(length=36), nullable=True),
    sa.Column('reviewed_by', sa.String(length=36), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['representative_id'], ['representatives.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('representative_id', 'field_key', 'period', name='uq_claim_field_period')
    )
    op.create_index('ix_claim_rep', 'representative_claims', ['representative_id'], unique=False)
    op.create_index('ix_claim_status', 'representative_claims', ['verification_status'], unique=False)


def downgrade() -> None:
    op.drop_index('ix_claim_status', table_name='representative_claims')
    op.drop_index('ix_claim_rep', table_name='representative_claims')
    op.drop_index('ix_promise_state_status', table_name='promises')
    op.drop_index('ix_promise_slug', table_name='promises')
    op.drop_index('ix_promise_rep', table_name='promises')
    op.drop_index('ix_assignment_status', table_name='task_assignments')
    op.drop_index('ix_assignment_profile', table_name='task_assignments')
    op.drop_index('ix_rep_state_house', table_name='representatives')
    op.drop_index('ix_rep_slug', table_name='representatives')
    op.drop_index('ix_rep_published', table_name='representatives')
    op.drop_index('ix_rep_constituency', table_name='representatives')
    op.drop_index('ix_confirmation_unique', table_name='report_confirmations')
    op.drop_index('ix_confirmation_report', table_name='report_confirmations')
    op.drop_index('ix_reply_thread', table_name='forum_replies')
    op.drop_index('ix_reply_status', table_name='forum_replies')
    op.drop_index('ix_attempt_citizen', table_name='academy_quiz_attempts')
    op.drop_index('ix_volunteer_state', table_name='volunteer_profiles')
    op.drop_index('ix_signature_petition', table_name='petition_signatures')
    op.drop_index('ix_vote_target', table_name='forum_votes')
    op.drop_index('ix_thread_status', table_name='forum_threads')
    op.drop_index('ix_thread_slug', table_name='forum_threads')
    op.drop_index('ix_thread_category', table_name='forum_threads')
    op.drop_index('ix_registration_ticket', table_name='event_registrations')
    op.drop_index('ix_registration_event', table_name='event_registrations')
    op.drop_index('ix_constituency_state_house', table_name='constituencies')
    op.drop_index('ix_constituency_slug', table_name='constituencies')
    op.drop_index('ix_report_status', table_name='citizen_reports')
    op.drop_index('ix_report_slug', table_name='citizen_reports')
    op.drop_index('ix_report_service', table_name='citizen_reports')
    op.drop_index('ix_report_place', table_name='citizen_reports')
    op.drop_index('ix_lesson_course', table_name='academy_lessons')
    op.drop_index('ix_enrollment_citizen', table_name='academy_enrollments')
    op.drop_index('ix_task_state', table_name='volunteer_tasks')
    op.drop_index('ix_task_slug', table_name='volunteer_tasks')
    op.drop_index('ix_task_skill_status', table_name='volunteer_tasks')
    op.drop_index('ix_template_kind', table_name='tool_templates')
    op.drop_index('ix_template_key', table_name='tool_templates')
    op.drop_index('ix_generation_template', table_name='tool_generation_log')
    op.drop_index('ix_search_type', table_name='search_docs')
    op.drop_index('ix_search_state', table_name='search_docs')
    op.drop_index('ix_document_state', table_name='research_documents')
    op.drop_index('ix_document_slug', table_name='research_documents')
    op.drop_index('ix_document_published', table_name='research_documents')
    op.drop_index('ix_document_kind', table_name='research_documents')
    op.drop_index('ix_petition_status', table_name='petitions')
    op.drop_index('ix_petition_state', table_name='petitions')
    op.drop_index('ix_petition_slug', table_name='petitions')
    op.drop_index('ix_event_when', table_name='events')
    op.drop_index('ix_event_state', table_name='events')
    op.drop_index('ix_event_slug', table_name='events')
    op.drop_index('ix_correction_status', table_name='corrections')
    op.drop_index('ix_correction_entity', table_name='corrections')
    op.drop_index('ix_constitution_published', table_name='constitution_articles')
    op.drop_index('ix_constitution_part', table_name='constitution_articles')
    op.drop_index('ix_constitution_number', table_name='constitution_articles')
    op.drop_index('ix_consent_subject', table_name='consent_records')
    op.drop_index('ix_consent_created', table_name='consent_records')
    op.drop_index('ix_certificate_holder', table_name='certificates')
    op.drop_index('ix_certificate_code', table_name='certificates')
    op.drop_index('ix_ai_log_created', table_name='ai_question_log')
    op.drop_index('ix_ai_cache_key', table_name='ai_answer_cache')
    op.drop_index('ix_course_slug', table_name='academy_courses')
    op.drop_table('representative_claims')
    op.drop_table('promises')
    op.drop_table('task_assignments')
    op.drop_table('representatives')
    op.drop_table('report_confirmations')
    op.drop_table('forum_replies')
    op.drop_table('academy_quiz_attempts')
    op.drop_table('volunteer_profiles')
    op.drop_table('petition_signatures')
    op.drop_table('forum_votes')
    op.drop_table('forum_threads')
    op.drop_table('event_registrations')
    op.drop_table('constituencies')
    op.drop_table('citizen_reports')
    op.drop_table('academy_quizzes')
    op.drop_table('academy_lessons')
    op.drop_table('academy_enrollments')
    op.drop_table('volunteer_tasks')
    op.drop_table('tool_templates')
    op.drop_table('tool_generation_log')
    op.drop_table('search_docs')
    op.drop_table('research_documents')
    op.drop_table('petitions')
    op.drop_table('parties')
    op.drop_table('forum_categories')
    op.drop_table('events')
    op.drop_table('corrections')
    op.drop_table('constitution_articles')
    op.drop_table('consent_records')
    op.drop_table('citizens')
    op.drop_table('certificates')
    op.drop_table('ai_question_log')
    op.drop_table('ai_answer_cache')
    op.drop_table('academy_courses')
